---
- name: Include prereq trasks
  ansible.builtin.include_tasks: prereqs.yml

- name: configure firewall for JBCS ports
  become: yes
  ansible.posix.firewalld:
    port: "{{ port }}"
    permanent: true
    state: enabled
    immediate: yes
  loop:
    - "80/tcp"
    - "443/tcp"
    - "6666/tcp"
  loop_control:
    loop_var: port

- name: Import install tasks
  ansible.builtin.include_tasks: install.yml

- name: Import SSL configuration tasks
  ansible.builtin.include_tasks: ssl.yml

- name: "Start HTTPd Service"
  become: yes
  ansible.builtin.service:
    name: "{{ jbcs_service_name }}.service"
    state: started
    enabled: yes

- name: "Wait for all used ports to be open"
  ansible.builtin.wait_for:
    port: "{{ item }}"
    delay: 0
  loop:
    - 80
    - 443
    - 6666
  when:
    - check_jbcs_port is defined

- name: "Ensures mod_cluster configuration is deployed"
  ansible.builtin.template:
    src: templates/mod_cluster.conf.j2
    dest: "{{ httpd.home }}/httpd/conf.d/mod_cluster.conf"
    owner: "{{ httpd.user.name }}"
    group: "{{ httpd.group.name }}"
    mode: 0640
  when: jbcs_mod_cluster_enable
  notify:
    - 'expire mod_cluster cache and restart'
