---
- name: Include install packages
  ansible.builtin.include_tasks: fastpackages.yml
  vars:
    packages_list:
      - firewalld

- name: Ensure that firewalld service is running
  become: true
  ansible.builtin.systemd:
    name: firewalld
    enabled: yes
    state: started
